### ISSUE TITLE
Not working on windows (10)

### ISSUE THREAD

**Issue by nakshay** [0xAX/notificator#18]
Hi @0xAX ,

I tried to use below code on MacOS it worked, but its not working on windows, Specifically I am using windows 10.

```
notifier := notificator.New(notificator.Options{
		DefaultIcon: "icon/default.png",
		AppName:     "Tracker",
	})
notifier.Push(title, body, iconPath, notificator.UR_CRITICAL)
```

**Comment by l1f** [comment]
I think it is because windows is not implemented.

**Comment by nakshay** [comment]
Readme says "Windows with growlnotify", anyway I don't need it now
